project:
  type: book
  output-dir: docs

book:
  title: "Crear tablas de resumen en R"
  author: "Dirección Nacional de Planeación y Estadística"
  chapters:
    - index.qmd
    - "Conceptos Basicos.qmd"
    - "Agregar Partes.qmd"
    - "Funciones Referencia.qmd"
    - "gt avanzado.qmd"
    - Referencias.qmd
  favicon: 'Imagenes/Logos/Escudo_UNAL.png'

bibliography: references.bib

format:
  html:
    theme: cerulean
    fontsize: 1.1em
    linestretch: 1.7
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt

editor: visual

lang: es




