project:
  type: book
  output-dir: docs

book:
  title: "Crear tablas de resumen en R"
  author: "Dirección Nacional de Planeación y Estadística"
  chapters:
    - index.qmd
    - "Conceptos Basicos.qmd"
    - "Agregar Partes.qmd"
    - Referencias.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt

editor: visual

lang: es




